<a href="https://colab.research.google.com/github/Patanjaligokhale/Projects/blob/main/pitorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__


'2.2.1+cu121'

In [ ]:
#scalar= torch.tensor(6)
#scalar.ndim
#vector = torch.tensor([6.6])
#vector.shape
matrix= torch.tensor([[1,2],[3,4]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [ ]:
randomtensor = torch.rand(size=(3,3))
randomtensor, randomtensor.dtype, randomtensor.ndim

(tensor([[0.5512, 0.0613, 0.6620],
         [0.8196, 0.4384, 0.1608],
         [0.8022, 0.2443, 0.4824]]),
 torch.float32,
 2)

In [ ]:
some_tensor= torch.rand(3,4)
print (some_tensor)
print(f"shape of tensor: {some_tensor.shape}")
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"device temsor is stored on:{some_tensor.device}")

tensor([[3.3593e-02, 3.3102e-01, 3.0029e-01, 7.2674e-02],
        [3.4976e-01, 5.2121e-01, 9.5396e-01, 1.9107e-01],
        [7.3242e-04, 9.9857e-01, 8.0161e-01, 3.3856e-01]])
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device temsor is stored on:cpu


In [ ]:
tensor= torch.tensor([1,2,3])
#print(f"{tensor+10}")
#tensor = tensor-10
#torch.mul(tensor,10)
#print(tensor,"*",tensor)
#print("equals:", tensor*tensor)
tensor.shape
tensor.matmul(tensor)

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype= torch.float32)
tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]], dtype=torch.float32)
print(tensor_A)
print(tensor_B.T)
torch.mm(tensor_A, tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)

#x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output: {output}")


Input shape: torch.Size([3, 2])

Output: tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [ ]:
x = torch.arange(0, 100, 10)

print(f"min: {x.min()}")
print(f"max:{x.max()}")
print(f"sum: {x.sum()}")
print(f"mean: {x.type(torch.float32).mean()}")


min: 0
max:90
sum: 450
mean: 45.0


In [ ]:
x= torch.arange(1.,8.)
x_stacked = torch.stack([x,x,x],dim=0)
#x_stacked

In [ ]:
x= torch.arange(1,10).reshape(1,3,3)
print(f"First sqauare bracket:{x[0]}")
print(f"2nd square bracket:{x[0][0]}")
print(f"3rd square bracket:{x[0][0][0]}")


First sqauare bracket:tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2nd square bracket:tensor([1, 2, 3])
3rd square bracket:1


In [ ]:
import torch
rand_tens = torch.rand(7,7)
rand_tens2 = torch.rand(1,7)
matrixm = torch.matmul(rand_tens,rand_tens2.T)
matrixm

tensor([[1.1198],
        [0.9144],
        [0.8527],
        [0.8358],
        [1.7485],
        [1.1006],
        [1.3293]])

In [ ]:
torch.manual_seed(0)
rand_tens = torch.rand(7,7)


rand_tens2 = torch.rand(1,7)

matrixmm = torch.matmul(rand_tens, rand_tens2.T)
matrixmm

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])